version: "3.9"

services:
  db:
    image: postgres:16
    container_name: mixq-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mixq_user
      POSTGRES_PASSWORD: mixq_pass
      POSTGRES_DB: mixq
    ports:
      - "5432:5432"
    volumes:
      - mixq_pgdata:/var/lib/postgresql/data

volumes:
  mixq_pgdata:
